shared:
  task: "SINGLE_LABEL_CLASSIFICATION"

  # project configurations for experiment tracking - wandb
  project: "learning-agency-lab-automated-essay-scoring-2"
  entity: "gaohn-teaching-mlops"
  name: null
  job_type: "train" # CHANGE
  tags: null
  group: null
  notes: null
  mode: null

  # data configurations
  ## filepaths
  train_filepath: "lal/data/train.csv"
  valid_filepath: null
  pretraining_data_filepath: null
  external_data_filepath: "lal/data/persuade_2.0_human_scores_demo_id_github.csv"
  predicted_prompt_filepath: "lal/data/predicted_prompt.csv"
  train_topic_filepath: "lal/data/train_topic.csv"
  topics_map_filepath: "lal/conf/topics_map.json"

  system_prompt: "Please read the following essay and assign a score of 1,2,3,4,5,6 where 6 is the best. Output only a single number with no explanation.\n\n"
  essay_id: "essay_id"
  full_text: "full_text"
  score: "score"
  label: "label"
  description: "description"
  num_labels: 6 # CHANGE

  # split/resample strategy
  resample_strategy: "StratifiedKFold"
  resample_params:
    n_splits: 7
    shuffle: true
    random_state: 42
  # resample_strategy: "GroupKFold" # "StratifiedKFold" "StratifiedGroupKFold" # CHANGE
  # resample_params:
  #   n_splits: 7 # CHANGE
  #   # shuffle: true
  #   # random_state: 42
  group_by: null
  stratify_by: "score"
  fold_column: "fold"
  target_column: "label"
  fold: 0
  debug_samples: 128

  # from_pretrained configurations
  padding_side: "right" # CHANGE

  # kwargs to tokenizer(...)
  max_length: 1024 # CHANGE
  truncation: true
  return_tensors: null
  add_special_tokens: true
  padding: "max_length"

  return_tokenized_text: true

  # peft
  task_type: "SEQ_CLS"
  inference_mode: false
  r: 32
  lora_alpha: 16
  lora_dropout: 0.1
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj"]
  bias: "none"
  modules_to_save: ["score"]

  # **kwargs to model(...)
  force_download: false
  device_map: "auto"
  torch_dtype: "float32" # CHANGE
  load_in_4bit: false
  output_hidden_states: false
  output_attentions: false

  # pooler
  pooler_type: null
  pooler_config: {}

  # criterion
  criterion: null # CHANGE
  criterion_config: {}

  pretrained_model_name_or_path: "microsoft/deberta-v3-small" # CHANGE
  load_backbone_only: false
  cache_dir: "/root/.cache/huggingface"
  target_artifacts_dir: "/artifacts"
  verbose: true
  show_model_summary: true
  dry_run: true
  default: false

  load_from: null
  inference: false
  use_lora: false
  num_layers_to_remove: null
  reinitialize_n_layers: 0
  num_layers_to_freeze: null
  freeze_embeddings: false

  # seed
  seed: 42
  seed_torch: true
  set_torch_deterministic: false

  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1e-6
  bf16: false
  data_seed: null
  dataloader_num_workers: 0
  disable_tqdm: false
  do_eval: true
  do_predict: false
  do_train: true
  eval_strategy: "steps"
  eval_steps: null
  fp16: false
  full_determinism: false
  gradient_accumulation_steps: 1 # CHANGE
  gradient_checkpointing: false
  greater_is_better: true # CHANGE
  include_tokens_per_second: false
  label_smoothing_factor: 0.0
  learning_rate: 0.00001 # CHANGE
  load_best_model_at_end: true
  logging_dir: null
  logging_first_step: true
  logging_steps: null
  logging_strategy: "steps"
  lr_scheduler_kwargs: {}
  lr_scheduler_type: "cosine" # CHANGE
  max_grad_norm: 1.0
  max_steps: null
  metric_for_best_model: "eval_qwk" # CHANGE
  num_train_epochs: 4 # CHANGE
  optim: "adamw_torch"
  output_dir: null
  overwrite_output_dir: true
  per_device_eval_batch_size: 16 # CHANGE
  per_device_train_batch_size: 16 # CHANGE
  prediction_loss_only: false
  report_to: "wandb"
  restore_callback_states_from_checkpoint: false
  resume_from_checkpoint: null # CHANGE
  save_only_model: false
  save_on_each_node: false
  save_safetensors: true
  save_steps: null
  save_strategy: "steps"
  save_total_limit: 3
  warmup_ratio: 0 # CHANGE
  warmup_steps: 0
  weight_decay: 0.01


  base_learning_rate: 0.00001 # CHANGE
  desired_effective_batch_size: 16
  enable_mixed_precision: true
